export const USER_ACTIONS = {
  GET_STUDENTS: "GET_STUDENTS",
  GET_STUDENTS_FAIL: "GET_STUDENTS_FAIL",
  GET_STUDENTS_START: "GET_STUDENTS_START",
  GET_STUDENTS_END: "GET_STUDENTS_END",
  GET_PROFILE_DETAILS: "GET_PROFILE_DETAILS",
  GET_PROFILE_FAIL: "GET_PROFILE_FAIL",
  GET_PROFILE_END: "GET_PROFILE_END",
  GET_PROFILE_START: "GET_PROFILE_START",
};
